try:
	print('raising')
	raise Exception(u'hello world')
except:
	print('caught')
